### ISSUE TITLE
Millennium bug

### ISSUE THREAD

**Issue by emaV** [nature/boomcatch#53]
Currently boomcatch rely on `qs` library to parse beacon data in `parseData` function and by default `qs` will only parse up to 1000 parameters.

This is not usually an issue in production but on dev you may have CSS and JS not combined and with the `restiming.js` plugin you may hit the above limit.

Raising the limit to 10K should solve the issue. See nature/boomcatch/pull/54

**Comment by philbooth** [comment]
Thanks again for reporting and fixing this; I've published a new release as version 2.2.1.
