### ISSUE TITLE
Remove the data normalisation process

### ISSUE THREAD

**Issue by philbooth** [nature/boomcatch#55]
My original thinking behind normalising the data was to make writing extensions easier; the boomerang format is necessarily terse to reduce the size of its payload so I wanted to pass something through that was easier to work with.

However, I now think that was a mistake for the following reasons:

1. It adds little value because nobody is writing extensions.
2. It separates extensions from the boomerang data format, which is documented and familiar to people.
3. It only passes through data from the round trip, navigation timing and resource timing plugins.

Reason number 3 is the really big one. Normalisation also places an extra maintenance burden on this project as it must ensure it matches up to any changes made to boomerang.

Making the normalisation step an extension point can't be done without affecting the reusability of the other extensions, since they expect a uniform data format.

Hence the only sane thing to do, I think, is delete normalisation entirely. Sadly it is a bigger job than simple deletion, because all of the extensions must be updated to use the boomerang data format.

**Comment by emaV** [comment]
What about deferring the normalization down to the extension pipeline?

Maybe adding a specific filter `normalise.js` and use it as default so that what you get from `filter(data)` correspond to the current [`filter(normaliseData(data))`](//github.com/nature/boomcatch/blob/master/src/index.js#L656). This doesn't affect at all other current extension.

If and when someone needs to access the raw data will simply select the `unfiltered.js` filter and voilà we solve even the #7.

**Comment by philbooth** [comment]
That introduces problems because normalisation affects subsequent extensions in a way that compromises their reusability.

At the moment, a mapper is a mapper. You can plug in any mapper in any context and it will work, because the input data format is always the same. The `statsd` mapper can always be used when you want to send data to statsd.

However, if normalisation is an extension point, then mappers can no longer rely on the input data format. Sometimes they will fail. Now a `statsd` mapper is required for each normaliser, duplicating logic and opening the possibility of issues when logic is changed in one place but not in another.

So in that sense normalisation is really not an extension point like the other things are, because it violates modularity and introduces coupling.

Hence I think this is a binary choice. Either we get rid of normalisation entirely or we keep it in, but there is no middle ground imho.

**Comment by emaV** [comment]
I'm currently testing the filter approach in my [fork](//github.com/emaV/boomcatch/tree/dev-denormalise). It seems to work indeed; only 8 test are failing but I didn't investigate too much yet.

The interesting part is that I'm able to run `boomcatch --port 8080` without any change on the mappers code and it works with `har` and `waterfall` as well. I kept the `unfiltered.js` to propagate raw data from the beacon down on the pipeline, but it is not the default now.

I understand the point about the mappers that needs to rely on consistent data, but even with the current configuration I can mess around with the data with a crazy filter. I think that the important thing is that the default data (so without any filter) should be digested by the current mappers and this is what happen with the "normalise as default filter" approach.

Maybe it's not elegant as solution and another step in the pipeline would be a more appropriate approach.

**Comment by philbooth** [comment]
Oh, that sounds cool. Will take a closer look at what you've done tomorrow, maybe I didn't understand / appreciate exactly what you were saying? :)

**Comment by philbooth** [comment]
Resolved in #58.
